// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNNXF6vsR7T4DJQf_3QnbY7FKoBggKgUo',
    appId: '1:283327600463:web:439b2ff126c09a5b0a573a',
    messagingSenderId: '283327600463',
    projectId: 'control-habitos1',
    authDomain: 'control-habitos1.firebaseapp.com',
    storageBucket: 'control-habitos1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnKOYPwT-GXGHx6hjX-d2_WOO8GoZv4uA',
    appId: '1:283327600463:android:7f4635ce1b75614f0a573a',
    messagingSenderId: '283327600463',
    projectId: 'control-habitos1',
    storageBucket: 'control-habitos1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgB-u4s_BjLloChLJotyEyF9FnBERC7JU',
    appId: '1:283327600463:ios:2cb870c0a73104740a573a',
    messagingSenderId: '283327600463',
    projectId: 'control-habitos1',
    storageBucket: 'control-habitos1.firebasestorage.app',
    iosBundleId: 'com.example.controlHabitos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgB-u4s_BjLloChLJotyEyF9FnBERC7JU',
    appId: '1:283327600463:ios:2cb870c0a73104740a573a',
    messagingSenderId: '283327600463',
    projectId: 'control-habitos1',
    storageBucket: 'control-habitos1.firebasestorage.app',
    iosBundleId: 'com.example.controlHabitos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNNXF6vsR7T4DJQf_3QnbY7FKoBggKgUo',
    appId: '1:283327600463:web:7b40eb78f310579c0a573a',
    messagingSenderId: '283327600463',
    projectId: 'control-habitos1',
    authDomain: 'control-habitos1.firebaseapp.com',
    storageBucket: 'control-habitos1.firebasestorage.app',
  );

}